Imports System
Imports System.Collections.Generic
Imports System.Data
Imports System.Data.SqlClient
Imports System.ComponentModel
Namespace SIS.DB
  <DataObject()>
  Partial Public Class ProDoc

    'PLM
    Public Property t_docn As String = ""
    Public Property prjID As String = ""
    Public Property t_revn As String = ""
    Public Property t_dsca As String = ""
    Public Property t_bsfd As String = ""
    Public Property t_acdt As String = ""
    Public Property t_rsfd As String = ""
    Public Property t_lrrd As String = ""
    Public Property t_dttl As String = ""
    Public Property t_resp As String = ""
    Public Property t_appb As String = ""
    Public Property t_chkb As String = ""
    Public Property t_drwb As String = ""
    Public Property t_stat As String = ""
    Public Property t_wfst As String = ""
    Public Property t_soft As String = ""

    Public Property ProjectID As String = ""

    Public Property element As String = ""

    Public Property t_dcrn As String = ""
    Public Property t_cspa As String = ""
    Public Property t_reqs As String = ""
    Public Property t_comp As String = ""
    Public Property t_crea As String = ""
    Public Property t_user As String = ""
    Public Property t_cprj As String = ""


    Public Property t_tran As String = ""
    Public Property t_type As String = ""
    Public Property t_logn As String = ""
    Public Property t_subj As String = ""
    Public Property t_apsu As String = ""
    Public Property t_issu As String = ""
    Public Property t_retn As String = ""
    Public Property t_isby As String = ""
    Public Property t_isdt As String = ""

    Public Property t_sarn As String = ""
    Public Property t_draw As String = ""
    Public Property t_prep As String = ""
    Public Property t_rper As String = ""
    Public Property t_apby As String = ""

    Public Property t_rcno As String = ""
    Public Property t_item As String = ""
    Public Property IMechanical As String = ""
    Public Property IStructure As String = ""
    Public Property IPiping As String = ""
    Public Property IProcess As String = ""
    Public Property IC_I As String = ""
    Public Property IElectrical As String = ""
    Public Property IQuality As String = ""

    Public Property TT_CSPA As String = ""
    Public Property TT_ENGS As String = ""
    Public Property TT_TITTLE As String = ""
    Public Property TT_DEPT As String = ""

    Public Property Owner_Dept As String = ""
    Public Property t_dprj As String = ""






    Public Shared Function GetProData(ByVal det As String, ByVal PrjID As String) As List(Of ProDoc)
      Dim userG As String = ""

      Dim UserID As String = HttpContext.Current.Session("LoginID")
      Dim UserIDT As Integer = 0
      Try
        UserIDT = Convert.ToInt32(UserID)
      Catch ex As Exception

      End Try

      If PrjID = "" Then Return Nothing

      Dim mRet As New List(Of SIS.DB.ProDoc)

      Dim Sql As String = ""
      Using Con As SqlConnection = New SqlConnection(SIS.SYS.SQLDatabase.DBCommon.GetBaaNConnectionString())
        Con.Open()
        Select Case det

          Case "Process_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='PRC' and t_cprj in ('" & PrjID & "') "
          Case "Mechanical_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='MEC' and t_cprj in ('" & PrjID & "') "
          Case "Structure_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='STR' and t_cprj in ('" & PrjID & "') "
          Case "Piping_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='PIP' and t_cprj in ('" & PrjID & "') "
          Case "Electrical_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='ELE' and t_cprj in ('" & PrjID & "') "
          Case "CI_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='C&I' and t_cprj in ('" & PrjID & "') "
          Case "Total_Total"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where t_cprj in ('" & PrjID & "') "

          Case "Process_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='PRC' and t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"
          Case "Mechanical_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='MEC' and t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"
          Case "Structure_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='STR' and t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"
          Case "Piping_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='PIP' and t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"
          Case "Electrical_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='ELE' and t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"
          Case "CI_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='C&I' and t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"
          Case "Total_Released"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where t_cprj in ('" & PrjID & "') and t_acdt <>'1970-01-01 00:00:00.000'"

          Case "Process_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='PRC' and t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"
          Case "Mechanical_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='MEC' and t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"
          Case "Structure_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='STR' and t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"
          Case "Piping_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='PIP' and t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"
          Case "Electrical_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='ELE' and t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"
          Case "CI_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where  t_resp ='C&I' and t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"
          Case "Total_Pending"
            Sql = "select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,t_acdt,CONVERT(VARCHAR(10), t_rsfd, 103) as t_rsfd,t_lrrd from tdmisg140200 where t_cprj in ('" & PrjID & "') and t_acdt ='1970-01-01 00:00:00.000'"

          Case "Process_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_resp ='PRC' and t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"
          Case "Mechanical_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_resp ='MEC' and t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"
          Case "Structure_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_resp ='STR' and t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"
          Case "Piping_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_resp ='PIP' and t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"
          Case "Electrical_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_resp ='ELE' and t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"
          Case "CI_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_resp ='C&I' and t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"
          Case "Total_Due"
            Sql = " Select t_docn,t_revn,t_dsca,t_bsfd,t_rsfd,t_acdt From tdmisg140200 Where t_cprj In ('" & PrjID & "') And t_acdt = convert(datetime,'01/01/1970',103) And  convert(date,t_rsfd) = convert(date,getdate())"

          Case "Process_Ontime"

            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='PRC'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Mechanical_Ontime"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd, t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd  "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='MEC'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Structure_Ontime"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='STR'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "


          Case "Piping_Ontime"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='PIP'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "


          Case "Electrical_Ontime"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd, t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='ELE'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "CI_Ontime"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd, t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='C&I'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Total_Ontime"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd, t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt <= t_rsfd 		 "
            Sql &= "	then 1 else 0 end "


          Case "Process_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='PRC'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Mechanical_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='MEC'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Structure_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='STR'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Piping_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='PIP'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Electrical_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='ELE'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "CI_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	And t_resp='C&I'	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "Total_Delayed"
            Sql = "		Select t_docn,t_revn,t_dsca,CONVERT(VARCHAR(10), t_bsfd, 103) as t_bsfd,CONVERT(VARCHAR(10), t_rsfd, 103) As t_rsfd,t_acdt,CONVERT(VARCHAR(10), t_lrrd, 103) As t_lrrd "
            Sql &= "	From tdmisg140200 "
            Sql &= "	Where "
            Sql &= "	t_cprj In ('" & PrjID & "')  "
            Sql &= "	and t_acdt <> convert(datetime,'01/01/1970',103)	"
            Sql &= "  And 1 =   case when t_acdt > t_rsfd 		 "
            Sql &= "	then 1 else 0 end "

          Case "PLM_CHART"
            Sql = "		SELECT        t_docn, t_revn, t_dttl, t_resp, t_appb, t_chkb, t_drwb, (CASE t_stat WHEN 1 THEN 'Submitted' WHEN 2 THEN 'Item Released' WHEN 3 THEN 'Drg Released' WHEN 4 THEN 'Expired' END) AS t_stat, t_type, "
            Sql &= "	(CASE t_wfst WHEN 1 THEN 'Under Design' WHEN 2 THEN 'Submitted' WHEN 3 THEN 'Under Review' WHEN 4 THEN 'Under Approve' WHEN 5 THEN 'Released' WHEN 6 THEN 'Withdrawn' WHEN 7 THEN 'Under Revision' WHEN "
            Sql &= "	8 THEN 'Superseded' WHEN 9 THEN 'Under DCR' END) AS t_wfst, t_soft "
            Sql &= "	FROM            tdmisg001200 AS aa "
            Sql &= "	WHERE        (t_cprj = '" & PrjID & "') AND (t_revn =	"
            Sql &= "  (SELECT        MAX(t_revn) AS Expr1 		 "
            Sql &= "	FROM            tdmisg001200 AS bb "
            Sql &= "  WHERE        (t_docn = aa.t_docn))) "
            Sql &= "  order by t_wfst desc "

          Case "DCR_CHART"

            Sql = " select t_dcrn,t_dsca,rec.t_cspa as element,(case t_stat "
            Sql &= " when 1 then 'Under Creation' "
            Sql &= "  when 2 then 'Under Approve' "
            Sql &= " when 3 then 'Approved' "
            Sql &= " end) as t_stat, (case t_reqs "
            Sql &= " when 001 then 'Work Stopped' "
            Sql &= " when 002 then 'Work can proceed' "
            Sql &= " when 003 then 'Work will stop' "
            Sql &= " end) as t_reqs,(case t_comp "
            Sql &= " when 001 then 'Work Stopped' "
            Sql &= " when 002 then 'Manufacturing Yet to start' "
            Sql &= " when 003 then 'Under manufacturing' "
            Sql &= " when 004    then 'Ready for dispatch' "
            Sql &= " when 005 then 'Material Recieved at site' "
            Sql &= " when 006 then 'Erection completed' "
            Sql &= " when 007 then 'Boiler commisioned and in operation' "
            Sql &= " when 008 then 'In design stage' "
            Sql &= " when 009 then 'Budget available in element 50060100' "
            Sql &= " when 010 then 'under progress' "
            Sql &= " when 011 then 'not applicable' "
            Sql &= " when 012 then 'Budget avilable in element' "
            Sql &= " end) as t_comp,t_crea,t_user,"
            Sql &= " (case ttppdm090200.t_sort "
            Sql &= "            when 'MECH-SUGAR' then 'MECHANICAL' "
            Sql &= "            when 'ELECTRICAL' then 'ELECTRICAL' "
            Sql &= "            when 'MECHANICAL' then 'MECHANICAL' "
            Sql &= "            WHEN 'PROCESS-STOKER' Then 'MECHANICAL' "
            Sql &= "            when 'OTHERS' then 'OTHERS' "
            Sql &= "            WHEN 'PROCESS' then 'PROCESS' "
            Sql &= "            WHEN 'STRUCTURE' THEN 'STRUCTURE' "
            Sql &= "            WHEN 'PIPING' THEN 'PIPING' "
            Sql &= "            WHEN 'C & I' THEN 'C&I' "
            Sql &= "            WHEN 'INSTRUMENTATION' THEN 'C&I' "
            Sql &= "            WHEN 'EPC' THEN 'EPC' "
            Sql &= "            WHEN 'C&I' THEN 'C&I' "
            Sql &= "            WHEN 'ELE' THEN 'ELECTRICAL' "
            Sql &= "            WHEN 'SERVICE' THEN 'OTHERS' "
            Sql &= "            else 'OTHERS' "
            Sql &= "            end) as Owner_Dept "
            Sql &= "            From tdmisg114200 as rec "
            Sql &= "LEFT JOIN ttppdm090200 "
            Sql &= "on ttppdm090200.t_cspa = rec.t_cspa "
            Sql &= "            Where t_cprj=('" & PrjID & "') "

          'Case "DCR_CHART"
          '  Sql = " select t_dcrn,t_dsca,t_cspa,(case t_stat "
          '  Sql &= " when 1 then 'Under Creation' "
          '  Sql &= "  when 2 then 'Under Approve' "
          '  Sql &= " when 3 then 'Approved' "
          '  Sql &= " end) as t_stat, (case t_reqs "
          '  Sql &= " when 001 then 'Work Stopped' "
          '  Sql &= " when 002 then 'Work can proceed' "
          '  Sql &= " when 003 then 'Work will stop' "
          '  Sql &= " end) as t_reqs,(case t_comp "
          '  Sql &= " when 001 then 'Work Stopped' "
          '  Sql &= " when 002 then 'Manufacturing Yet to start' "
          '  Sql &= " when 003 then 'Under manufacturing' "
          '  Sql &= " when 004    then 'Ready for dispatch' "
          '  Sql &= " when 005 then 'Material Recieved at site' "
          '  Sql &= " when 006 then 'Erection completed' "
          '  Sql &= " when 007 then 'Boiler commisioned and in operation' "
          '  Sql &= " when 008 then 'In design stage' "
          '  Sql &= " when 009 then 'Budget available in element 50060100' "
          '  Sql &= " when 010 then 'under progress' "
          '  Sql &= " when 011 then 'not applicable' "
          '  Sql &= " when 012 then 'Budget avilable in element' "
          '  Sql &= " end) as t_comp,t_crea,t_user from tdmisg114200 "
          '  Sql &= " where (t_cprj = '" & PrjID & "')"
          '  Sql &= " order by t_stat "

          Case "IDMS_CHART"
            Sql = "Select t_tran,(Case t_type   "
            Sql &= "            when 1 then 'Customer' "
            Sql &= "            when 2 then 'Internal' "
            Sql &= "            When 3 Then 'Site' "
            Sql &= "            when 4 then 'Vendor' "
            Sql &= "            End) As t_type,t_subj,(Case t_stat "
            Sql &= "            when 1 then 'Returned' "
            Sql &= "            When 2 Then 'Free' "
            Sql &= "            when 3 then 'Under Approval' "
            Sql &= "            When 4 Then 'Under Issue' "
            Sql &= "            when 5 then 'Issued' "
            Sql &= "            When 6 Then 'Patial Released' "
            Sql &= "            when 7 then 'Received' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat,t_user,(case tdmisg130200.t_dept"
            Sql &= " when 'PRC' then 'PROCESS' "
            Sql &= "when 'ELE' then 'ELECTRICAL' "
            Sql &= "when 'MEC' then 'MECHANICAL' "
            Sql &= "when 'OTHERS' then 'OTHERS' "
            Sql &= "WHEN 'STR' THEN 'STRUCTURE' "
            Sql &= "WHEN 'PIP' THEN 'PIPING' "
            Sql &= "WHEN 'C&I' THEN 'C&I' "
            Sql &= " else 'OTHERS' "
            Sql &= "end) AS Owner_Dept,t_apsu,(Case t_issu "
            Sql &= "            when 001 then  'Hard copy by Hand' "
            Sql &= "            When 002 Then 'Hard copy by Courier' "
            Sql &= "            when 003 then 'e mail' "
            Sql &= "            When 004 Then 'Uploaded in ftp server' "
            Sql &= "            when 005 then 'Uploaded in client or consultant portal' "
            Sql &= "            When 006 Then 'Vault' "
            Sql &= "            when 007 then 'Open KM (DMS)' "
            Sql &= "            End) As t_issu,t_retn,t_isby,t_isdt from tdmisg131200 "
            Sql &= "LEFT JOIN tdmisg130200 "
            Sql &= "on tdmisg131200.t_user= tdmisg130200.t_logn "
            Sql &= "where (t_tran LIKE ('SMD%') OR t_tran LIKE ('BOI%') OR t_tran LIKE ('APC%') OR t_tran LIKE ('EPC%') OR t_tran LIKE ('PCD%')) "
            Sql &= " and t_dprj = ('" & PrjID & "')"

          Case "IDMSC_CHART"
            Sql = "Select t_tran,(Case t_type   "
            Sql &= "            When 1 Then 'Customer' "
            Sql &= "            when 2 then 'Internal' "
            Sql &= "            When 3 Then 'Site' "
            Sql &= "            when 4 then 'Vendor' "
            Sql &= "            End) As t_type,t_subj,(Case t_stat "
            Sql &= "            when 1 then 'Returned' "
            Sql &= "            When 2 Then 'Free' "
            Sql &= "            when 3 then 'Under Approval' "
            Sql &= "            When 4 Then 'Under Issue' "
            Sql &= "            when 5 then 'Issued' "
            Sql &= "            When 6 Then 'Patial Released' "
            Sql &= "            when 7 then 'Received' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat,t_user,(case tdmisg130200.t_dept"
            Sql &= " when 'PRC' then 'PROCESS' "
            Sql &= "when 'ELE' then 'ELECTRICAL' "
            Sql &= "when 'MEC' then 'MECHANICAL' "
            Sql &= "when 'OTHERS' then 'OTHERS' "
            Sql &= "WHEN 'STR' THEN 'STRUCTURE' "
            Sql &= "WHEN 'PIP' THEN 'PIPING' "
            Sql &= "WHEN 'C&I' THEN 'C&I' "
            Sql &= " else 'OTHERS' "
            Sql &= "end) AS Owner_Dept,t_apsu,(Case t_issu "
            Sql &= "            when 001 then  'Hard copy by Hand' "
            Sql &= "            When 002 Then 'Hard copy by Courier' "
            Sql &= "            when 003 then 'e mail' "
            Sql &= "            When 004 Then 'Uploaded in ftp server' "
            Sql &= "            when 005 then 'Uploaded in client or consultant portal' "
            Sql &= "            When 006 Then 'Vault' "
            Sql &= "            when 007 then 'Open KM (DMS)' "
            Sql &= "            End) As t_issu,t_retn,t_isby,t_isdt from tdmisg131200 "
            Sql &= "LEFT JOIN tdmisg130200 "
            Sql &= "on tdmisg131200.t_user= tdmisg130200.t_logn "
            Sql &= "where (t_tran LIKE ('SMD%') OR t_tran LIKE ('BOI%') OR t_tran LIKE ('APC%') OR t_tran LIKE ('EPC%') OR t_tran LIKE ('PCD%')) "
            Sql &= " and t_dprj = ('" & PrjID & "') and t_type =1"


          Case "IDMSI_CHART"
            Sql = "Select t_tran,(Case t_type   "
            Sql &= "            when 1 then 'Customer' "
            Sql &= "            when 2 then 'Internal' "
            Sql &= "            When 3 Then 'Site' "
            Sql &= "            when 4 then 'Vendor' "
            Sql &= "            End) As t_type,t_subj,(Case t_stat "
            Sql &= "            when 1 then 'Returned' "
            Sql &= "            When 2 Then 'Free' "
            Sql &= "            when 3 then 'Under Approval' "
            Sql &= "            When 4 Then 'Under Issue' "
            Sql &= "            when 5 then 'Issued' "
            Sql &= "            When 6 Then 'Patial Released' "
            Sql &= "            when 7 then 'Received' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat,t_user,(case tdmisg130200.t_dept"
            Sql &= " when 'PRC' then 'PROCESS' "
            Sql &= "when 'ELE' then 'ELECTRICAL' "
            Sql &= "when 'MEC' then 'MECHANICAL' "
            Sql &= "when 'OTHERS' then 'OTHERS' "
            Sql &= "WHEN 'STR' THEN 'STRUCTURE' "
            Sql &= "WHEN 'PIP' THEN 'PIPING' "
            Sql &= "WHEN 'C&I' THEN 'C&I' "
            Sql &= " else 'OTHERS' "
            Sql &= "end) AS Owner_Dept,t_apsu,(Case t_issu "
            Sql &= "            when 001 then  'Hard copy by Hand' "
            Sql &= "            When 002 Then 'Hard copy by Courier' "
            Sql &= "            when 003 then 'e mail' "
            Sql &= "            When 004 Then 'Uploaded in ftp server' "
            Sql &= "            when 005 then 'Uploaded in client or consultant portal' "
            Sql &= "            When 006 Then 'Vault' "
            Sql &= "            when 007 then 'Open KM (DMS)' "
            Sql &= "            End) As t_issu,t_retn,t_isby,t_isdt from tdmisg131200 "
            Sql &= "LEFT JOIN tdmisg130200 "
            Sql &= "on tdmisg131200.t_user= tdmisg130200.t_logn "
            Sql &= "where (t_tran LIKE ('SMD%') OR t_tran LIKE ('BOI%') OR t_tran LIKE ('APC%') OR t_tran LIKE ('EPC%') OR t_tran LIKE ('PCD%')) "
            Sql &= " and t_dprj = ('" & PrjID & "') and t_type =2"

          Case "IDMSS_CHART"
            Sql = "Select t_tran,(Case t_type   "
            Sql &= "            when 1 then 'Customer' "
            Sql &= "            when 2 then 'Internal' "
            Sql &= "            When 3 Then 'Site' "
            Sql &= "            when 4 then 'Vendor' "
            Sql &= "            End) As t_type,t_subj,(Case t_stat "
            Sql &= "            when 1 then 'Returned' "
            Sql &= "            When 2 Then 'Free' "
            Sql &= "            when 3 then 'Under Approval' "
            Sql &= "            When 4 Then 'Under Issue' "
            Sql &= "            when 5 then 'Issued' "
            Sql &= "            When 6 Then 'Patial Released' "
            Sql &= "            when 7 then 'Received' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat,t_user,(case tdmisg130200.t_dept"
            Sql &= " when 'PRC' then 'PROCESS' "
            Sql &= "when 'ELE' then 'ELECTRICAL' "
            Sql &= "when 'MEC' then 'MECHANICAL' "
            Sql &= "when 'OTHERS' then 'OTHERS' "
            Sql &= "WHEN 'STR' THEN 'STRUCTURE' "
            Sql &= "WHEN 'PIP' THEN 'PIPING' "
            Sql &= "WHEN 'C&I' THEN 'C&I' "
            Sql &= " else 'OTHERS' "
            Sql &= "end) AS Owner_Dept,t_apsu,(Case t_issu "
            Sql &= "            when 001 then  'Hard copy by Hand' "
            Sql &= "            When 002 Then 'Hard copy by Courier' "
            Sql &= "            when 003 then 'e mail' "
            Sql &= "            When 004 Then 'Uploaded in ftp server' "
            Sql &= "            when 005 then 'Uploaded in client or consultant portal' "
            Sql &= "            When 006 Then 'Vault' "
            Sql &= "            when 007 then 'Open KM (DMS)' "
            Sql &= "            End) As t_issu,t_retn,t_isby,t_isdt from tdmisg131200 "
            Sql &= "LEFT JOIN tdmisg130200 "
            Sql &= "on tdmisg131200.t_user= tdmisg130200.t_logn "
            Sql &= "where (t_tran LIKE ('SMD%') OR t_tran LIKE ('BOI%') OR t_tran LIKE ('APC%') OR t_tran LIKE ('EPC%') OR t_tran LIKE ('PCD%')) "
            Sql &= " and t_dprj = ('" & PrjID & "') and t_type=3"

          Case "IDMSV_CHART"
            Sql = " Select t_tran,(Case t_type "
            Sql &= " when 1 then 'Customer' "
            Sql &= " when 2 then 'Internal' "
            Sql &= " When 3 Then 'Site' "
            Sql &= " when 4 then 'Vendor' "
            Sql &= " End) As t_type,t_logn,t_subj,(Case t_stat"
            Sql &= " when 1 then 'Returned' "
            Sql &= " When 2 Then 'Free' "
            Sql &= " when 3 then 'Under Approval' "
            Sql &= " When 4 Then 'Under Issue' "
            Sql &= " when 5 then 'Issued' "
            Sql &= " When 6 Then 'Patial Released' "
            Sql &= " when 7 then 'Received' "
            Sql &= " when 8 then 'Closed' "
            Sql &= " End) As t_stat,t_user,t_apsu,(Case t_issu "
            Sql &= " when 001 then	'Hard copy by Hand'"
            Sql &= " When 002 Then 'Hard copy by Courier'"
            Sql &= " when 003 then 'e mail'"
            Sql &= " When 004 Then 'Uploaded in ftp server'"
            Sql &= " when 005 then 'Uploaded in client or consultant portal'"
            Sql &= " When 006 Then 'Vault'"
            Sql &= " when 007 then 'Open KM (DMS)'"
            Sql &= " End) As t_issu,t_retn,t_isby,t_isdt from tdmisg131200 where t_dprj =('" & PrjID & "') and t_type =4"

          Case "IDMSII_CHART"

            Sql &= "Select t_tran,(Case t_type   "
            Sql &= "            when 1 then 'Customer' "
            Sql &= "            when 2 then 'Internal' "
            Sql &= "            When 3 Then 'Site' "
            Sql &= "            when 4 then 'Vendor' "
            Sql &= "            End) As t_type,t_subj,(Case t_stat "
            Sql &= "            when 1 then 'Returned' "
            Sql &= "            When 2 Then 'Free' "
            Sql &= "            when 3 then 'Under Approval' "
            Sql &= "            When 4 Then 'Under Issue' "
            Sql &= "            when 5 then 'Issued' "
            Sql &= "            When 6 Then 'Patial Released' "
            Sql &= "            when 7 then 'Received' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat,t_user,(case tdmisg130200.t_dept"
            Sql &= " when 'PRC' then 'PROCESS' "
            Sql &= "when 'ELE' then 'ELECTRICAL' "
            Sql &= "when 'MEC' then 'MECHANICAL' "
            Sql &= "when 'OTHERS' then 'OTHERS' "
            Sql &= "WHEN 'STR' THEN 'STRUCTURE' "
            Sql &= "WHEN 'PIP' THEN 'PIPING' "
            Sql &= "WHEN 'C&I' THEN 'C&I' "
            Sql &= " else 'OTHERS' "
            Sql &= "end) AS Owner_Dept,t_apsu,(Case t_issu "
            Sql &= "            when 001 then  'Hard copy by Hand' "
            Sql &= "            When 002 Then 'Hard copy by Courier' "
            Sql &= "            when 003 then 'e mail' "
            Sql &= "            When 004 Then 'Uploaded in ftp server' "
            Sql &= "            when 005 then 'Uploaded in client or consultant portal' "
            Sql &= "            When 006 Then 'Vault' "
            Sql &= "            when 007 then 'Open KM (DMS)' "
            Sql &= "            End) As t_issu,t_retn,t_isby,t_isdt from tdmisg131200 "
            Sql &= "LEFT JOIN tdmisg130200 "
            Sql &= "on tdmisg131200.t_user= tdmisg130200.t_logn "
            Sql &= "where (t_tran LIKE ('SMD%') OR t_tran LIKE ('BOI%') OR t_tran LIKE ('APC%') OR t_tran LIKE ('EPC%') OR t_tran LIKE ('PCD%')) "
            Sql &= " and t_dprj = ('" & PrjID & "') and t_stat =5"


          Case "SAR_CHART"

            Sql = "Select t_sarn, t_draw,(case ttppdm090200.t_sort "
            Sql &= "            when 'MECH-SUGAR' then 'MECHANICAL' "
            Sql &= "            when 'ELECTRICAL' then 'ELECTRICAL' "
            Sql &= "            when 'MECHANICAL' then 'MECHANICAL' "
            Sql &= "            WHEN 'PROCESS-STOKER' Then 'MECHANICAL' "
            Sql &= "            when 'OTHERS' then 'OTHERS' "
            Sql &= "            WHEN 'PROCESS' then 'PROCESS' "
            Sql &= "            WHEN 'STRUCTURE' THEN 'STRUCTURE' "
            Sql &= "            WHEN 'PIPING' THEN 'PIPING' "
            Sql &= "            WHEN 'C & I' THEN 'C&I' "
            Sql &= "            WHEN 'INSTRUMENTATION' THEN 'C&I' "
            Sql &= "            WHEN 'EPC' THEN 'EPC' "
            Sql &= "            WHEN 'C&I' THEN 'C&I' "
            Sql &= "            WHEN 'ELE' THEN 'ELECTRICAL' "
            Sql &= "            WHEN 'SERVICE' THEN 'OTHERS' "
            Sql &= "            else 'OTHERS' "
            Sql &= "            end) as Owner_Dept,"
            Sql &= "            (Case t_stat "
            Sql &= "           When 1 Then 'Created' "
            Sql &= "          when 2 then 'Under Review' "
            Sql &= "         When 3 Then 'Under Approval' "
            Sql &= "           when 4 then 'Approved' "
            Sql &= "          When 5 Then 'Not Applicable' "
            Sql &= "           End) As t_stat,rec.t_cspa as element, t_prep,t_rper,t_apby  "
            Sql &= "         From ttpisg074200 AS rec "
            Sql &= "LEFT JOIN ttppdm090200 "
            Sql &= "on ttppdm090200.t_cspa = rec.t_cspa "
            Sql &= "            Where t_cprj=('" & PrjID & "') "
            Sql &= "            Order by t_sarn"
          Case "IDMSP_CHART"

            Sql = "Select t_rcno, t_revn, t_cprj, t_item, Left(LTrim(t_item), 8) As element, "
            Sql &= "(case ttppdm090200.t_sort "
            Sql &= "            when 'MECH-SUGAR' then 'MECHANICAL' "
            Sql &= "            when 'ELECTRICAL' then 'ELECTRICAL' "
            Sql &= "            when 'MECHANICAL' then 'MECHANICAL' "
            Sql &= "            WHEN 'PROCESS-STOKER' Then 'MECHANICAL' "
            Sql &= "            when 'OTHERS' then 'OTHERS' "
            Sql &= "            WHEN 'PROCESS' then 'PROCESS' "
            Sql &= "            WHEN 'STRUCTURE' THEN 'STRUCTURE' "
            Sql &= "            WHEN 'PIPING' THEN 'PIPING' "
            Sql &= "            WHEN 'C & I' THEN 'C&I' "
            Sql &= "            WHEN 'INSTRUMENTATION' THEN 'C&I' "
            Sql &= "            WHEN 'EPC' THEN 'EPC' "
            Sql &= "            WHEN 'C&I' THEN 'C&I' "
            Sql &= "            WHEN 'ELE' THEN 'ELECTRICAL' "
            Sql &= "            WHEN 'SERVICE' THEN 'OTHERS' "
            Sql &= "            else 'OTHERS' "
            Sql &= "            end) as Owner_Dept,"
            Sql &= "            (case t_sent_1 "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IMechanical, "
            Sql &= "            (case t_sent_2  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IStructure, "
            Sql &= "            (case t_sent_3  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IPiping, "
            Sql &= "            (case t_sent_4  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IProcess, "
            Sql &= "            (case t_sent_5  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            when 2 then '-'   "
            Sql &= "            End ) As IC_I, "
            Sql &= "            (case t_sent_6  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            when 2 then '-'   "
            Sql &= "            End ) As IElectrical, "
            Sql &= "            (case t_sent_7 "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            when 2 then '-'   "
            Sql &= "            End ) As IQuality, (Case t_stat "
            Sql &= "            when 1 then 'Submitted' "
            Sql &= "            when 2 then 'Document linked' "
            Sql &= "            when 3 then 'Under Evaluation' "
            Sql &= "            when 4 then 'Comments Submitted' "
            Sql &= "            when 5 then 'Technically Cleared' "
            Sql &= "            when 6 then 'Transmittal Issued' "
            Sql &= "            when 7 then 'Superceded' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat "
            Sql &= "            From tdmisg134200 As rec "
            Sql &= " LEFT JOIN ttppdm090200 "
            Sql &= " on ttppdm090200.t_cspa= LEFT(Ltrim(rec.t_item),8) "
            Sql &= "            Where rec.t_rcno Like ('REC%') and t_cprj=('" & PrjID & "') "

          Case "IDMSO_CHART"
            Sql = "Select t_rcno,t_revn,t_cprj,t_item,LEFT(Ltrim(t_item),8) as element, "
            Sql &= "(case ttppdm090200.t_sort "
            Sql &= "            when 'MECH-SUGAR' then 'MECHANICAL' "
            Sql &= "            when 'ELECTRICAL' then 'ELECTRICAL' "
            Sql &= "            when 'MECHANICAL' then 'MECHANICAL' "
            Sql &= "            WHEN 'PROCESS-STOKER' Then 'MECHANICAL' "
            Sql &= "            when 'OTHERS' then 'OTHERS' "
            Sql &= "            WHEN 'PROCESS' then 'PROCESS' "
            Sql &= "            WHEN 'STRUCTURE' THEN 'STRUCTURE' "
            Sql &= "            WHEN 'PIPING' THEN 'PIPING' "
            Sql &= "            WHEN 'C & I' THEN 'C&I' "
            Sql &= "            WHEN 'INSTRUMENTATION' THEN 'C&I' "
            Sql &= "            WHEN 'EPC' THEN 'EPC' "
            Sql &= "            WHEN 'C&I' THEN 'C&I' "
            Sql &= "            WHEN 'ELE' THEN 'ELECTRICAL' "
            Sql &= "            WHEN 'SERVICE' THEN 'OTHERS' "
            Sql &= "            else 'OTHERS' "
            Sql &= "            end) as Owner_Dept,"
            Sql &= "            (case t_sent_1 "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IMechanical, "
            Sql &= "            (case t_sent_2  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IStructure, "
            Sql &= "            (case t_sent_3  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IPiping, "
            Sql &= "            (case t_sent_4  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            When 2 Then '-'   "
            Sql &= "            End ) As IProcess, "
            Sql &= "            (case t_sent_5  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            when 2 then '-'   "
            Sql &= "            End ) As IC_I, "
            Sql &= "            (case t_sent_6  "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            when 2 then '-'   "
            Sql &= "            End ) As IElectrical, "
            Sql &= "            (case t_sent_7 "
            Sql &= "            when 1 then 'Response Pending' "
            Sql &= "            when 2 then '-'   "
            Sql &= "            End ) As IQuality, (Case t_stat "
            Sql &= "            when 1 then 'Submitted' "
            Sql &= "            when 2 then 'Document linked' "
            Sql &= "            when 3 then 'Under Evaluation' "
            Sql &= "            when 4 then 'Comments Submitted' "
            Sql &= "            when 5 then 'Technically Cleared' "
            Sql &= "            when 6 then 'Transmittal Issued' "
            Sql &= "            when 7 then 'Superceded' "
            Sql &= "            when 8 then 'Closed' "
            Sql &= "            End) As t_stat "
            Sql &= "            From tdmisg134200 As rec "
            Sql &= " LEFT JOIN ttppdm090200 "
            Sql &= " on ttppdm090200.t_cspa= LEFT(Ltrim(rec.t_item),8) "
            Sql &= "            Where rec.t_rcno Like ('REP%') and t_cprj=('" & PrjID & "') "


          Case = "ELEMENT_CHART"

            Sql = " select ttpisg063200.t_cspa AS TT_CSPA,( "
            Sql &= "         case ttpisg063200.t_engs "
            Sql &= "         when 1 then 'Free' "
            Sql &= "         when 2 then 'Partial' "
            Sql &= "         when 3 then 'Complete' "
            Sql &= "         end "
            Sql &= "         ) as TT_ENGS,ttppdm090200.t_desc AS TT_TITTLE,(case ttppdm090200.t_sort "
            Sql &= "  when 'MECH-SUGAR' then 'MECHANICAL' "
            Sql &= " when 'ELECTRICAL' then 'ELECTRICAL' "
            Sql &= " when 'MECHANICAL' then 'MECHANICAL' "
            Sql &= " WHEN 'PROCESS-STOKER' Then 'MECHANICAL' "
            Sql &= " when 'OTHERS' then 'OTHERS' "
            Sql &= " WHEN 'PROCESS' then 'PROCESS' "
            Sql &= " WHEN 'STRUCTURE' THEN 'STRUCTURE' "
            Sql &= " WHEN 'PIPING' THEN 'PIPING' "
            Sql &= " WHEN 'C & I' THEN 'C&I' "
            Sql &= " WHEN 'INSTRUMENTATION' THEN 'C&I' "
            Sql &= " WHEN 'EPC' THEN 'EPC' "
            Sql &= " WHEN 'C&I' THEN 'C&I' "
            Sql &= " WHEN 'ELE' THEN 'ELECTRICAL' "
            Sql &= " WHEN 'SERVICE' THEN 'OTHERS' "
            Sql &= "  else 'OTHERS' "
            Sql &= "  end) AS TT_DEPT from ttpisg063200 "
            Sql &= " LEFT JOIN ttppdm090200 "
            Sql &= " on ttppdm090200.t_cspa= ttpisg063200.t_cspa "
            Sql &= "         where ttpisg063200.t_cprj =('" & PrjID & "') and ttpisg063200.t_appl=1 "






        End Select

            Using Cmd As SqlCommand = Con.CreateCommand()
          Cmd.CommandType = CommandType.Text
          Cmd.CommandText = Sql
          Dim rd As SqlDataReader = Cmd.ExecuteReader
          While (rd.Read)
            mRet.Add(New ProDoc(rd))
          End While
        End Using
      End Using
      Return mRet
    End Function


    Public Sub New(ByVal Reader As SqlDataReader)
      Try
        For Each pi As System.Reflection.PropertyInfo In Me.GetType.GetProperties
          If pi.MemberType = Reflection.MemberTypes.Property Then
            Try
              Dim Found As Boolean = False
              For I As Integer = 0 To Reader.FieldCount - 1
                If Reader.GetName(I).ToLower = pi.Name.ToLower Then
                  Found = True
                  Exit For
                End If
              Next
              If Found Then
                If Convert.IsDBNull(Reader(pi.Name)) Then
                  Select Case Reader.GetDataTypeName(Reader.GetOrdinal(pi.Name))
                    Case "decimal"
                      CallByName(Me, pi.Name, CallType.Let, "0.00")
                    Case "bit"
                      CallByName(Me, pi.Name, CallType.Let, Boolean.FalseString)
                    Case Else
                      CallByName(Me, pi.Name, CallType.Let, String.Empty)
                  End Select
                Else
                  CallByName(Me, pi.Name, CallType.Let, Reader(pi.Name))
                End If
              End If
            Catch ex As Exception
            End Try
          End If
        Next
      Catch ex As Exception
      End Try
    End Sub
    Public Sub New()
    End Sub
  End Class
End Namespace
